apiVersion: apps/v1
kind: Deployment
metadata:
  name: nbody-gpu-benchmark
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nbody-gpu-benchmark
  template:
    metadata:
      labels:
        app: nbody-gpu-benchmark
    spec:
      runtimeClassName: nvidia
      containers:
      - name: cuda-container
        image: nvcr.io/nvidia/k8s/cuda-sample:nbody
        args: ["nbody", "-gpu", "-benchmark"]
        resources:
          limits:
            nvidia.com/gpu: 1
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: all
